import Header from "@/components/common/Header";

export const metadata = {
  title: "Public Layout",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
